---
# vars file for server_setup
new_user: admind # replace with desired username
pub_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAW48gnUerYKVZoQBWR7zmNYzbjqexUk7SHf/u88B6Uo stevekunze@protonmail.com" # replace with desired pubkey
packages: # insert a list of packages here
  - micro
  - sudo
  - htop
  - unzip
  - fastfetch