---
# vars file for server_setup
user: steve # replace with desired username
pacman_packages: # insert a list of packages here
  - micro
  - fastfetch
  - vscodium
  - alacritty
  - helix
  - keepassxc
  - obs-studio
  - discord
  - yt-dlp
  - openssh-server
  - id3v2
  - yay
  - obsidian
  - nextcloud-client
  - steam
  - restic
  - mc
  - fzf
  - zoxide
  - exa
  - starship
  - libreoffice-still
  - zsh
yay_packages:
  - brave-bin
  - librewolf-bin