[servers]
paperless.familiekunze.home ansible_python_interpreter=/usr/bin/python3.13
nas.familiekunze.home ansible_python_interpreter=/usr/bin/python3.13
traefik.familiekunze.home ansible_python_interpreter=/usr/bin/python3.13
adguard.familiekunze.home ansible_python_interpreter=/usr/bin/python3.13
docker.familiekunze.home ansible_python_interpreter=/usr/bin/python3.13
[servers:vars]
ansible_connection=ssh
ansible_user=admind
#ansible_ssh_pass=:WAyF2kXe3_ie.
ansible_ssh_private_key_file=/home/steve/.ssh/vms_ed25519
[pve]
pve.familiekunze.home ansible_python_interpreter=/usr/bin/python3.13
[pve:vars]
ansible_connection=ssh
ansible_user=root
ansible_ssh_private_key_file=/home/steve/.ssh/pve_ed25519
